name: Citizens
main: com.fullwall.Citizens.Citizens
version: 1.0.8
author: fullwall
commands:
    npc:
        description: Performs various NPC-related commands.
        usage: |
                    The command was not recognised. Did you type in it in correctly?
                    See /citizens help for a list of commands.   
    basic:
        description: Basic NPC help menu.
        usage: |
                    The command was not recognised. Did you type in it in correctly?
                    See /citizens help for a list of commands.
    blacksmith:
        description: Performs various Blacksmith NPC-related commands.
        usage: |
                        The command was not recognised. Did you type it in correctly?
                        See /citizens help for a list of commands.           
    trader:
        description: Performs various Trader NPC-related commands.
        usage: |
                        The command was not recognised. Did you type it in correctly?
                        See /citizens help for a list of commands.
    healer:
        description: Performs various Healer NPC-related commands.
        usage: |
                        The command was not recognised. Did you type it in correctly?
                        See /citizens help for a list of commands.
    wizard:
        description: Performs various Wizard NPC-related commands.
        usage: |
                        The command was not recognised. Did you type it in correctly?
                        See /citizens help for a list of commands.
    quester:
        description: Performs various Quester NPC-related commands.
        usage: |
                        The command was not recognised. Did you type it in correctly?
                        See /citizens help for a list of commands.
    toggle:
        description: Toggles between various NPC states.
        aliases: [t, tog, togg]
        usage: |
                        The command was not recognised. The correct syntax is
                        /<command> [type]
    citizens:
        description: Performs Citizens-related commands.
        usage: |
                    You typed the command incorrectly. It should be /<command> help.