name: Citizens
main: com.citizens.Citizens
version: 1.0.9
authors: [fullwall, aPunch]
softdepend: [Permissions]
commands:
    npc:
        description: Performs various NPC-related commands.
        usage: |
                    The command was not recognised. Was it typed in correctly?
                    See /basic help for a list of commands.   
    basic:
        description: Basic NPC help menu.
        usage: |
                    The command was not recognised. Was it typed in correctly?
                    See /basic help for a list of commands.
    blacksmith:
        description: Performs various Blacksmith NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /blacksmith help for a list of commands.           
    trader:
        description: Performs various Trader NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /trader help for a list of commands.
    guard:
        description: Performs various Guard NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /guard help for a list of commands.
    healer:
        description: Performs various Healer NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /healer help for a list of commands.
    wizard:
        description: Performs various Wizard NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /wizard help for a list of commands.
    quests:
        description: Performs player-quest related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /citizens help for a list of commands.
    quester:
        description: Performs various Quester NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /quester help for a list of commands.
    toggle:
        description: Toggles between various NPC states.
        aliases: [t, tog]
        usage: |
                        The command was not recognised. The correct syntax is
                        /<command> [type]
    citizens:
        description: Performs Citizens-related commands.
        usage: |
                    You typed the command incorrectly. It should be /<command> help.
permissions:
    citizens.*:
        default: false
        children:
            citizens.admin: true
    citizens.trader.*:
        children:
            citizens.trader.create: true
            citizens.trader.modify: true
            citizens.trader.use: true
    citizens.guard.*:
        children:
            citizens.guard.create: true
            citizens.guard.modify: true
            citizens.guard.use: true
    citizens.basic.*:
        children:
            citizens.basic.create: true
            citizens.basic.modify: true
            citizens.basic.use: true
    citizens.quester.*:
        children:
            citizens.quester.create: true
            citizens.quester.modify: true
            citizens.quester.use: true
    citizens.healer.*:
        children:
            citizens.healer.create: true
            citizens.healer.modify: true
            citizens.healer.use: true
    citizens.blacksmith.*:
        children:
            citizens.blacksmith.create: true
            citizens.blacksmith.modify: true
            citizens.blacksmith.use: true