name: Citizens
main: com.fullwall.Citizens.Citizens
version: 1.0.8
author: fullwall
commands:
    npc:
        description: Performs various NPC-related commands.
        usage: |
                    The command was not recognised. Did you type in it in correctly?
                    See /citizens [basic|trader] help [page] for a list of commands.
    trader:
        description: Performs various TraderNPC-related commands.
        usage: |
                        The command was not recognised. Did you type it in correctly?
                        See /citizens trader help [page] for a list of commands.
    toggle:
        description: Toggles between various NPC states.
        usage: |
                        The command was not recognised. The correct syntax is
                        /<command> [type]
    citizens:
        description: Performs Citizens-related commands.
        usage: |
                    Incorrect syntax. Type /citizens [basic|trader] help [page] for more info.
