name: Citizens
main: com.fullwall.Citizens.Citizens
version: 1.0.9
authors: [fullwall, NeonMaster, aPunch, TheMPC]
softdepend: [Permissions]
commands:
    npc:
        description: Performs various NPC-related commands.
        usage: |
                    The command was not recognised. Was it typed in correctly?
                    See /basic help for a list of commands.   
    basic:
        description: Basic NPC help menu.
        usage: |
                    The command was not recognised. Was it typed in correctly?
                    See /basic help for a list of commands.
    blacksmith:
        description: Performs various Blacksmith NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /blacksmith help for a list of commands.           
    trader:
        description: Performs various Trader NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /trader help for a list of commands.
    guard:
        description: Performs various Guard NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /guard help for a list of commands.
    healer:
        description: Performs various Healer NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /healer help for a list of commands.
    wizard:
        description: Performs various Wizard NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /wizard help for a list of commands.
    quests:
        description: Performs player-quest related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /citizens help for a list of commands.
    quester:
        description: Performs various Quester NPC-related commands.
        usage: |
                        The command was not recognised. Was it typed in correctly?
                        See /quester help for a list of commands.
    questedit:
        description: Enters quest-edit mode.
        usage: |
                        The command was not recognised. The correct syntax is
                        /<command>
    toggle:
        description: Toggles between various NPC states.
        aliases: [t, tog, togg]
        usage: |
                        The command was not recognised. The correct syntax is
                        /<command> [type]
    citizens:
        description: Performs Citizens-related commands.
        usage: |
                    You typed the command incorrectly. It should be /<command> help.